### ISSUE TITLE
How exactly do you use this?

### ISSUE THREAD

**Issue by AndrewWang996** [ayamflow/Kami-MangaDownloader#1]
Hi, I'm interested in using this application to download chapters of Toriko, but after I've downloaded and unzipped all the files, unzipped the kami app, and run the app, I'm not sure where to search the manga chapter titles. Could you provide better documentation on how to use this?

**Comment by QuanSushi** [comment]
Hey Andy,
sorry, but I'm not the dev if this project. I cloned it two years ago but never looked into it. I also only used it once. I believe I had to copy the manga url from one of the supported sites and paste them into the search bar.

**Comment by ayamflow** [comment]
Hey Andrew,
This is correct. You need to paste the URL to a given manga.
FYI, I'm not maintaining this project anymore – it was more of a test and never really released.
I'm working on something better but I need some time!
