### ISSUE TITLE
Mangafox.me downloads not starting

### ISSUE THREAD

**Issue by TheBryan2010** [ayamflow/Kami-MangaDownloader#2]
First off: Thank you for this amazing program! But I have an issue.

I would like to download some shows via Mangafox.me (as supported) but this doesn't work.
When putting them in the download queue, the chapters jump to 'ready' but they don't start.
I tried multiple manga shows, but it makes no difference.

Mangakeeper.net works great, but they don't have everything.

Thank you very much.

**Comment by ayamflow** [comment]
Hi there,
it might be because these mangas were licensed and thus not available on mangafox anymore.

I'm not supporting this project anymore. If you can, you could try MangaRipper of DoujinDownloader and see if it works better.
